// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9mbkEf_FQCDbVmf5q_7YidNtY2gyQDKE',
    appId: '1:604963624688:web:84435dfbdfe856296f1435',
    messagingSenderId: '604963624688',
    projectId: 'helpnow-cc592',
    authDomain: 'helpnow-cc592.firebaseapp.com',
    storageBucket: 'helpnow-cc592.firebasestorage.app',
    measurementId: 'G-TRKZM44VBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4HOMPK26WhBohB1lEoIIBks2Osj2dqtk',
    appId: '1:604963624688:android:9887f4e537bfa6176f1435',
    messagingSenderId: '604963624688',
    projectId: 'helpnow-cc592',
    storageBucket: 'helpnow-cc592.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX9EgSfIGNHKabse4jdBIPqG-yZ06e3aY',
    appId: '1:604963624688:ios:bcdd803c18e7bf806f1435',
    messagingSenderId: '604963624688',
    projectId: 'helpnow-cc592',
    storageBucket: 'helpnow-cc592.firebasestorage.app',
    iosBundleId: 'com.example.helpNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX9EgSfIGNHKabse4jdBIPqG-yZ06e3aY',
    appId: '1:604963624688:ios:bcdd803c18e7bf806f1435',
    messagingSenderId: '604963624688',
    projectId: 'helpnow-cc592',
    storageBucket: 'helpnow-cc592.firebasestorage.app',
    iosBundleId: 'com.example.helpNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9mbkEf_FQCDbVmf5q_7YidNtY2gyQDKE',
    appId: '1:604963624688:web:ded5e9569c8227616f1435',
    messagingSenderId: '604963624688',
    projectId: 'helpnow-cc592',
    authDomain: 'helpnow-cc592.firebaseapp.com',
    storageBucket: 'helpnow-cc592.firebasestorage.app',
    measurementId: 'G-0JLC9TYBM0',
  );

}